### ISSUE TITLE
Radeon GPU (macbook pro) Setup Question

### ISSUE THREAD

**Issue by suwangcompling** [hughperkins/tf-coriander#40]
Hi Hugh,

Thanks for your great work! 
I was wondering if you would be able to add a step-by-step tutorial on how to setup the code for using Radeon Pro GPU on MacBook with Tensorflow? It'd be very helpful!

Best,
Jacob

**Comment by hughperkins** [comment]
Do you mean, how to install it for you?  What happens if you install the wheel from https://github.com/hughperkins/tf-coriander/releases/tag/v0.17.3

**Comment by suwangcompling** [comment]
Thanks for the quick response.
Yes, I did that. However when I run the code multilayer_perceptron.py, I get Dead Kernel error every time. So wonder if I did some configurations incorrectly.

**Comment by suwangcompling** [comment]
turns out it was because i pointed tensorflow to the wrong GPU (the integrated Iris GPU).
the following prints out device list, so one knows which one gpu:0/1/... points to. sharing here just in case.
```
from tensorflow.python.client import device_lib

def show_all_devices():
    local_device_protos = device_lib.list_local_devices()
    for x in local_device_protos:
        print(x)
```

**Comment by hughperkins** [comment]
Cool! :-) . :+1:
