### ISSUE TITLE
The link to Mac Sierra package is borken

### ISSUE THREAD

**Issue by mutazmq** [hughperkins/tf-coriander#51]
[Mac Sierra link](https://github.com/hughperkins/tf-coriander/releases/download/v0.18.3/tensorflow-cl-v0.18.3-macsierra-python3.zip) doesn't work.

Another thing, I don't need to have any installation of Tensorflow to get Tensorflow-cl installed, correct?

**Comment by hughperkins** [comment]
> Mac Sierra link doesn't work.

Good spot :-) Thanks!  Try now?

> Another thing, I don't need to have any installation of Tensorflow to get Tensorflow-cl installed, correct?

Correct. You should uninstall any existing tensorflow package, or simply create a new virtualenv.
