### ISSUE TITLE
not work 'global_variables_initializer' in 'Intel(R) Iris(TM) Graphics 6100'

### ISSUE THREAD

**Issue by dal2** [hughperkins/tf-coriander#52]
> OpenCL platform: Apple
OpenCL device: Intel(R) Iris(TM) Graphics 6100
I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Found device 0 with properties: 
name: Intel(R) Iris(TM) Graphics 6100
major: -1 minor: -1 memoryClockRate (GHz) 1050
pciBusID 0000.0000
Total memory: 1.50GiB
Free memory: 384.00MiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:877] cannot enable peer access from device ordinal 0 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1011] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021] 0:   N 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1083] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Intel(R) Iris(TM) Graphics 6100, pci bus id: 0000.0000)
cl_driver DeviceAllocate 192937984
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/tensorflow-test/cnn.py", line 105, in <module>
    sess.run(tf.global_variables_initializer())
AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'

**Comment by cathalgarvey** [comment]
This isn't a device-related bug, it's a function interface in tensorflow that's changed. I can't recall the fix and I'm on mobile, but look up the global_variables_initializer function and you should find your fix.

On 16 June 2017 15:42:53 GMT+01:00, dal2 <notifications@github.com> wrote:
>> OpenCL platform: Apple
>OpenCL device: Intel(R) Iris(TM) Graphics 6100
>I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Found device 0
>with properties: 
>name: Intel(R) Iris(TM) Graphics 6100
>major: -1 minor: -1 memoryClockRate (GHz) 1050
>pciBusID 0000.0000
>Total memory: 1.50GiB
>Free memory: 384.00MiB
>I tensorflow/core/common_runtime/gpu/gpu_device.cc:877] cannot enable
>peer access from device ordinal 0 to device ordinal 0
>I tensorflow/core/common_runtime/gpu/gpu_device.cc:1011] DMA: 0 
>I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021] 0:   N 
>I tensorflow/core/common_runtime/gpu/gpu_device.cc:1083] Creating
>TensorFlow device (/gpu:0) -> (device: 0, name: Intel(R) Iris(TM)
>Graphics 6100, pci bus id: 0000.0000)
>cl_driver DeviceAllocate 192937984
>Traceback (most recent call last):
>File "/Users/user/PycharmProjects/tensorflow-test/cnn.py", line 105, in
><module>
>    sess.run(tf.global_variables_initializer())
>AttributeError: module 'tensorflow' has no attribute
>'global_variables_initializer'
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hughperkins/tf-coriander/issues/52

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by unoexperto** [comment]
@dal2 Did you make it work ?
