### ISSUE TITLE
Notes on Macbook Air -- Using Intel HD 5000

### ISSUE THREAD

**Issue by Dexdev08** [hughperkins/tf-coriander#55]
I've managed to install tf-coriander in OSX mavericks using the wheel file.
Thanks a lot!

Don't know where to put this - should i put this in the wiki?
The least I can do to document my experience for anyone who will come to this package.
Looking forward to keras v2.0 compatibility.

Keras ver 1.1.1
TF v0.11.0rc0

I realized the documentation in keras.io currently is already for the new version, as following examples there may not be updated.

example:
documentation:
keras.utils.to_categorical(y, num_classes)
model.fit - uses epochs as a parameter

keras v1.1.1
keras.utils.np_utils.to_categorical(y, nb_classes)
model.fit - uses nb_epoch as a parameter

**Comment by hughperkins** [comment]
Yes, wiki sounds good :-)

**Comment by Dexdev08** [comment]
OK!  Just saved it.  Will close this.

**Comment by hughperkins** [comment]
You mentioned in the other thread that it could be interesting to have keras 1.1.1 doc?  To what extent is https://faroit.github.io/keras-docs/1.1.1/ approximately what you are looking for?

**Comment by Dexdev08** [comment]
Yes, this is what I was looking for.

**Comment by hughperkins** [comment]
cool :-)

**Comment by Dexdev08** [comment]
Also a question - I'm going through all examples now - some examples, I encounter errors, but some seem to run just fine.  Where do you think I should log these?  (Also do you think it's worth to just upgrade my OS version to Sierra since Apple just stopped supporting this version last December?)

**Comment by hughperkins** [comment]
Can you paste the full output, including the command you are running, into a [gist](https://gist.github.com), and paste into a comment in this thread, one gist per failing example?

**Comment by Dexdev08** [comment]
1_Introduction/helloworld.py

<script src="https://gist.github.com/Dexdev08/576ff5a701878f18c42ec6ee49c85233.js"></script>

**Comment by Dexdev08** [comment]
3_NeuralNetworks/bidirectional_rnn.py

https://gist.github.com/Dexdev08/338dd6aca84a042e23e47ff39ebc7554

**Comment by hughperkins** [comment]
For the frist one, helloworld.py is not supported, since it contains strings. => normal, expected result

**Comment by hughperkins** [comment]
For the second one, can you define the envireonmetn variable `export COCL_OFFSETS_32BIT=1`, and retry please?  More information: https://github.com/hughperkins/coriander/blob/master/doc/options.md#cocl_offsets_32bit-for-beignet

**Comment by Dexdev08** [comment]
I think it has something to do with easycl?

https://gist.github.com/Dexdev08/5149c9097afe0d7df441c4d0b6cd834b

**Comment by hughperkins** [comment]
Background: easycl is a wrapper around OpenCL.  It is handling storing the failed kernel for us, and detecging the error, but the undelrying error is probably because buffer offsets are sent to the kernels as 64-bit integers by default, which beignet isnt a big fan of. See https://github.com/hughperkins/tf-coriander/issues/55#issuecomment-310842616 , above

**Comment by Dexdev08** [comment]
3_Neural_Networks/convolutional
https://gist.github.com/Dexdev08/fe27566859e8c088161f3ff6cf9d88c6

**Comment by Dexdev08** [comment]
I think only autoencoders work for my case - if it's because of the OS then i'll probably just upgrade in the next few days.  If it is a hardware limitation - at least good to know that I should acquire new hardware.

**Comment by hughperkins** [comment]
Please set the environment variable as above, and then retry

On 24 June 2017 15:57:01 BST, Dexdev08 <notifications@github.com> wrote:
>I think only autoencoders work for my case - if it's because of the OS
>then i'll probably just upgrade in the next few days.  If it is a
>hardware limitation - at least good to know that I should acquire new
>hardware.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hughperkins/tf-coriander/issues/55#issuecomment-310843292

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Dexdev08** [comment]
3_neural_networks_convolutional_network_COCL_error
https://gist.github.com/Dexdev08/d84fb4c4daa853e994493b8273ba3fcc

**Comment by Dexdev08** [comment]
This is the example from the keras documentation which worked
https://gist.github.com/Dexdev08/0f01bf364e47d860443690c120410268

**Comment by hughperkins** [comment]
Please set the env var, and retry bisectional rnn

On 24 June 2017 16:05:32 BST, Dexdev08 <notifications@github.com> wrote:
>This is the example from the keras documentation which worked
>https://gist.github.com/Dexdev08/0f01bf364e47d860443690c120410268
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hughperkins/tf-coriander/issues/55#issuecomment-310843807

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Dexdev08** [comment]
Hi Hugh,
this is the gist with the env var.
https://gist.github.com/Dexdev08/5149c9097afe0d7df441c4d0b6cd834b

**Comment by Dexdev08** [comment]
Hi Hugh!

I've finally upgraded my laptop to sierra and was able to run the tensorflow examples!
I would recommend to Macbook Air 2013 users to upgrade to Sierra.

Does this mean i can happily run more stuff on this?

Regards,
Dexter

**Comment by Dexdev08** [comment]
Just an update Hugh - I've tried a cpu version vs gpu version, the1.5GB memory and 384mb GPU memory of the macbook air is severely limiting for my experiments.

**Comment by hughperkins** [comment]
Right :) I'll close this then?

**Comment by Dexdev08** [comment]
Yes. Sad though i wanted to be an opencl proponent. - but im not even
knowledgable enouhh to help you out.
