### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by skn123** [hughperkins/tf-coriander#57]
Hugh, a simple HowTo would be helpful in building this repo. I was unable to follow it from the official webpage of tensorflow. I will illustrate what I did
a.) Used the CMake build from tensorflow 
b.) Had to modify your bzl files to correctly point it to the eigen file (apparently it is a .zip and not .tar.gz)
c.) Started the build. It went well until it reached Eigen
d.) It was complaining about a missing file "cuda_runtime.h". Now I presume your code should handle that. Is there any #ifdef that needs to be specified?

**Comment by hughperkins** [comment]
https://github.com/hughperkins/tf-coriander/blob/master/doc/build-from-source.md
