### ISSUE TITLE
Porting to Tensorflow r1.11

### ISSUE THREAD

**Issue by pint1022** [hughperkins/tf-coriander#90]
Hi
I am working on the project to upgrade tf-coriander to Tensorflow r1.11. I have made the changes to bazel BUILD structure to the point that the compilation is almost completed till the last step to link 'pywrap_tensorflow_internal.so'; then it reports "..._pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow7functor4TileIN5Eigen9GpuDeviceEiiEclERKS3_PNS_6TensorERKS7_N4absl4SpanIKiEE". BYW, I have only tile-functor commented out 'GOOGLE_CUDA' so far. It seems not to include the right dependency at rule 'tile_ops', but I have not found the right place to change it correctly.  Can someone shed some lights on the right direction?

thanks,
steven wang

**Comment by hughperkins** [comment]
I usually use liberal amounts of `grep` to try to find stuff. you can also use sites like http://demangler.com/ to unmangle the name, which can be quite helpful sometimes:

```
tensorflow::functor::Tile<Eigen::GpuDevice, int, int>::operator()(
    Eigen::GpuDevice const&, tensorflow::Tensor*,
    tensorflow::Tensor const&, absl::Span<int const>) const
```

**Comment by pint1022** [comment]
Hi, Hugh
Thank you for the information.
I have no clue where to look for the definition of the following function? Is it in Tensorflow or the third_party modules. Hope you could share some tips.

Thanks,
steven

**Comment by hughperkins** [comment]
Probably in tensorflow. Since tensorflow depends on eigen, whereas eigen
knows nothjng about tf.

**Comment by pint1022** [comment]
Hi, Hugh
I did a quick experiment to enable conv2d on the current version (0.11rc0). It is compiled fine, but has a runtime ‘undefined error’ on functor:
Tensorflow::functor::TransformFilter<Eigen::GpuDevice, float, int, 4>::operator()(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<float, 4, 1, int>, 16, Eigen::MakePointer>)

It is the type of error as I ran into on porting r1.11. If there are some clues on how to fix this one, it could be very helpful for the r1.11. porting.

Thanks,
steven

**Comment by hughperkins** [comment]
Well, if it is like the version i ported thsn you are gradually commenting
out #ifdef Googlecuda isbthat right? Probably need to uncommwnr a few more.

You can look at the commit history on the original port, and look at whar
things were uncommented at the same time. Might give some ideas on whwre to
look in tje new version.

**Comment by pint1022** [comment]
Hi, Hugh
I did some search of the errors. It is usually caused by ‘partial template specialization’ on the struct, e.g. ‘TransformFilter’ defined in ‘conv_2d.h’ as one of the examples.
It seems that ‘operator()’ of ‘TransformFilter is not properly linked. However, according to the ‘solution’ tips online, it should be solved by instantiating the classes/struct at the end of code, e.g. conv_ops.cc does the right thing to DECLARE_GPU_SPEC the struct.
So in my research,  it seems that the codes are correct; but it still runs into ‘undefined symbol’  issue. Do you have any clues on this matter?

Thanks,
steven

**Comment by hughperkins** [comment]
The diagnosis sounds correct. You will need to hunt through the files for
the missing declaration. I dojt know how yout version of the code works,
but in mine, it basically involved commenting / uncommenting declarations.
You can look at my commit history for examples. Mostly involved some
combination of grep, luck, and exhaustive search to find the appropriate
declarations...

**Comment by pint1022** [comment]
Right now, I work on the your branch of codes. Just commented out 3 files:
Conv_ops.cc
Conv_ops.h
Conv_ops_gpu.h

Which is related to enable ‘conv2D’. I did notice that those files are commented out before; but was disabled by adding ‘GOOGLE_CUDA’ later. Do you have reasons to do so?

Thanks,
steven

**Comment by hughperkins** [comment]
I dont remember low level details. The general principle i followed was:
- do not define google cuda
- choose some simple function to enable
- to enable it, comment out the ifdef google cuda guards around it
- somehow handle the compile errors resulting from this declaration needing
other declarations

Some functions were easier than others. If i got stuck, id revert, and try
a different function. And then come back to it later, once more functions
had been successfully enabled.

**Comment by hughperkins** [comment]
Also, if yiu are trying to enable gpu for convolutions, you could look at
the dnn branch. I dont remember what is in it. it needs the coriander-dnn
library/repo most likely.

**Comment by pint1022** [comment]
Hi, Hugh
Thanks for the tips. After enabling files one by one,  the build passed all missing functions issues. However, when it runs, it fails at:
Cl_gpu_executor::Creatednn()
[…Conv_ops.cc:526] check failed: stream->parent()->getConvolveAlgorithms(&algorithms)
..

I got corianderdnn nstalled on the system.

Do you have any tips?

steven

**Comment by pint1022** [comment]
Hi, Hugh
I got to the point to uncomment cl_dnn.cc/h. It seems closely linked to cudnn. Not sure how much it works.
steven

**Comment by absudabsu** [comment]
Any progress on this? Would be good to know where things stand.

**Comment by pint1022** [comment]
closed. The working repo is here: https://github.com/pint1022/tensorflow.
